version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: dogdb
      POSTGRES_USER: doguser
      POSTGRES_PASSWORD: dogpassword
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_DB_NAME=dogdb
      - DJANGO_DB_USER=doguser
      - DJANGO_DB_PASSWORD=dogpassword
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432

volumes:
  postgres_data:
